### ISSUE TITLE
privatek8s (infra.ci.jenkins.io) JDK tools installation are not tracked by `updatecli`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/kubernetes-management#4630]
While working on https://github.com/jenkins-infra/kubernetes-management/pull/4629, it appearead that the JDK tool installation versions are not tracked by `updatecli`

**Comment by SarathChandra24** [comment]
Hello,

I checked the update cli: [tools-jdk21.yaml](https://github.com/jenkins-infra/kubernetes-management/blob/main/updatecli/updatecli.d/jenkins-controllers/tools-jdk21.yaml#L27C19-L27C55) there is problem with the regex as per my knowledge.

Current expected pattern is "^jdk-21.(\\d*).(\\d*).(\\d*)+(\\d*)$" - which would expect there digits separated by '.' eg: jdk-21.0.2.9+13

but the releases are made [jdk-21.0.2+13](https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21.0.2%2B13) which would have the following pattern "^jdk-21.(\d*)\.(\d*)\.(\d*)\+(\d*)$"

I believe this might be the reason which updatecli is not tracking. I verified it in here https://regex101.com/

The following action is also commented which would not raise a pull request as per updatecli docs.
```yaml
actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump JDK21 version (Jenkins tools) on all controllers to {{ source "lastVersion" }}
    spec:
      labels:
        - dependencies
        - jdk21
```

Let me know if this issue talks about the same, I can create a PR.
